// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgoagyjmzwknqgxdyfzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnb2FneWptendrbnFneGR5ZnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDI0NjQsImV4cCI6MjA1OTY3ODQ2NH0.3ZTJF2bnEQOfvoYYnxnw4faLI5rM1UuUA_-byJVvQ-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);